//! Parity harness.
//!
//! Runs the codegraph pipeline against each fixture in
//! `tests/parity_fixtures/<name>/` and compares the resulting graph
//! against the committed `<name>/expected.json`.
//!
//! The harness doubles as a pre-port regression guard and (in later
//! phases) as a GitNexus-parity oracle. For the initial baseline every
//! `expected.json` is generated by running the *current* Rust pipeline.
//! Subsequent phases must not regress from those numbers.
//!
//! ## Running
//!
//! - `cargo test --test parity` — full suite, fails on any delta.
//! - `SPACEBOT_PARITY_REGEN=1 cargo test --test parity` — overwrite
//!   every fixture's `expected.json` with the current pipeline output.
//!   Commit the result only after reviewing the diff.
//!
//! ## Fixture layout
//!
//! Each fixture is a self-contained project tree:
//! ```text
//! tests/parity_fixtures/<name>/
//!   ...source files (any directory structure the fixture needs)...
//!   expected.json
//! ```
//! The pipeline walks the fixture root; the `expected.json` sits at the
//! root and is ignored by the walker because it has no source
//! extension.

use std::collections::{BTreeMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::Arc;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use tempfile::TempDir;
use tokio::sync::broadcast;

use spacebot::codegraph::db::{CodeGraphDb, SharedCodeGraphDb};
use spacebot::codegraph::pipeline;
use spacebot::codegraph::schema;
use spacebot::codegraph::types::CodeGraphConfig;

/// Snapshot of a project's graph shape. Compared structurally against
/// the committed baseline.
///
/// Fields use `BTreeMap` for stable JSON ordering so diffs are small
/// and deterministic when regenerating.
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
struct ParityReport {
    /// Label → node count. Labels with zero nodes are omitted so adding
    /// a new label to the schema doesn't silently perturb every fixture.
    node_counts: BTreeMap<String, u64>,

    /// Edge type → count.
    edge_counts: BTreeMap<String, u64>,

    /// Nodes that MUST exist with the specified properties. Empty for
    /// baseline fixtures; later phases populate this to lock invariants
    /// (e.g. "class `Foo` must be public").
    #[serde(default)]
    required_nodes: Vec<RequiredNode>,

    /// Edges that MUST exist. Same story — empty for baseline.
    #[serde(default)]
    required_edges: Vec<RequiredEdge>,
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
struct RequiredNode {
    qualified_name: String,
    label: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    visibility: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    is_exported: Option<bool>,
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
struct RequiredEdge {
    from_qname: String,
    to_qname: String,
    edge_type: String,
}

/// The project id used for every parity run. Kept constant so fixture
/// expectations are stable — tests always run against a fresh temp DB
/// so collisions are impossible.
const PARITY_PROJECT_ID: &str = "parity-fixture";

/// Path to the `tests/parity_fixtures/` directory. Resolved at build
/// time via `CARGO_MANIFEST_DIR` so fixtures travel with the repo.
fn fixtures_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/parity_fixtures")
}

/// Escape a string for use in a Cypher string literal.
fn cypher_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

/// Run the full pipeline against `fixture_dir` in a freshly-created
/// temporary LadybugDB, then read the graph back into a [`ParityReport`].
async fn run_pipeline_on_fixture(fixture_dir: &Path) -> Result<ParityReport> {
    let db_temp = TempDir::new().context("creating temp dir for parity DB")?;

    let db: SharedCodeGraphDb = Arc::new(
        CodeGraphDb::open(PARITY_PROJECT_ID, db_temp.path())
            .await
            .context("opening temp LadybugDB")?,
    );

    // Tests run offline — skip the fastembed model download so a
    // cold-cache machine doesn't stall on network init.
    let config = Arc::new(CodeGraphConfig {
        skip_embeddings: true,
        ..CodeGraphConfig::default()
    });
    // Larger buffer than the default so the pipeline doesn't drop
    // progress events while the test is busy awaiting completion.
    let (event_tx, _event_rx) = broadcast::channel(4096);

    let handle = pipeline::start_full_pipeline(
        PARITY_PROJECT_ID.to_string(),
        fixture_dir.to_path_buf(),
        db.clone(),
        config,
        event_tx,
    );

    let _stats = handle.wait().await.context("pipeline run failed")?;

    generate_report(&db).await
}

/// Read the graph out of the DB and summarize it into a structural
/// snapshot. Only counts and required-tuples are recorded — the raw
/// graph contents change across runs in ways that aren't load-bearing
/// (timestamps, internal ids), so snapshotting them verbatim would
/// produce noisy diffs.
async fn generate_report(db: &CodeGraphDb) -> Result<ParityReport> {
    let pid = cypher_escape(PARITY_PROJECT_ID);

    // Node counts: iterate the label catalogue instead of asking the DB
    // to list labels, because labels with zero nodes shouldn't appear
    // in the report but a naive `MATCH (n)` would surface the `Parameter`
    // label mid-pipeline.
    let mut node_counts = BTreeMap::new();
    for &label in schema::DISPLAY_NODE_LABELS {
        let count = db
            .query_scalar_i64(&format!(
                "MATCH (n:{label}) WHERE n.project_id = '{pid}' RETURN count(n)"
            ))
            .await
            .unwrap_or(Some(0))
            .unwrap_or(0);
        if count > 0 {
            node_counts.insert(label.to_string(), count as u64);
        }
    }

    // Edge counts: one query per edge type. We could group in a single
    // Cypher query but that complicates lbug::Value destructuring for
    // no real speed win on the small fixture graphs.
    let mut edge_counts = BTreeMap::new();
    for edge_type in KNOWN_EDGE_TYPES {
        let count = db
            .query_scalar_i64(&format!(
                "MATCH (a)-[r:CodeRelation]->() WHERE a.project_id = '{pid}' AND r.type = '{edge_type}' RETURN count(r)"
            ))
            .await
            .unwrap_or(Some(0))
            .unwrap_or(0);
        if count > 0 {
            edge_counts.insert(edge_type.to_string(), count as u64);
        }
    }

    Ok(ParityReport {
        node_counts,
        edge_counts,
        required_nodes: Vec::new(),
        required_edges: Vec::new(),
    })
}

/// Every edge type the schema currently emits. Kept as a static list
/// rather than derived from the DB so the harness catches regressions
/// where an edge type disappears from the output entirely (an empty
/// count is still a signal).
const KNOWN_EDGE_TYPES: &[&str] = &[
    "CONTAINS",
    "DEFINES",
    "CALLS",
    "IMPORTS",
    "EXTENDS",
    "IMPLEMENTS",
    "OVERRIDES",
    "HAS_METHOD",
    "HAS_PROPERTY",
    "ACCESSES",
    "USES",
    "HAS_PARAMETER",
    "DECORATES",
    "MEMBER_OF",
    "STEP_IN_PROCESS",
    "TESTED_BY",
    "ENTRY_POINT_OF",
    "HANDLES_ROUTE",
    "FETCHES",
    "QUERIES",
    "HANDLES_TOOL",
    "WRAPS",
    "OWNS",
];

/// Structural diff between two reports. Each entry is a single human-
/// readable line describing one mismatch; empty `Vec` = perfect match.
fn diff_reports(expected: &ParityReport, actual: &ParityReport) -> Vec<String> {
    let mut deltas = Vec::new();

    let all_labels: HashSet<&String> = expected
        .node_counts
        .keys()
        .chain(actual.node_counts.keys())
        .collect();
    for label in all_labels {
        let e = expected.node_counts.get(label).copied().unwrap_or(0);
        let a = actual.node_counts.get(label).copied().unwrap_or(0);
        if e != a {
            deltas.push(format!(
                "  node[{label}]: expected {e}, got {a} (delta {:+})",
                a as i64 - e as i64
            ));
        }
    }

    let all_edges: HashSet<&String> = expected
        .edge_counts
        .keys()
        .chain(actual.edge_counts.keys())
        .collect();
    for edge_type in all_edges {
        let e = expected.edge_counts.get(edge_type).copied().unwrap_or(0);
        let a = actual.edge_counts.get(edge_type).copied().unwrap_or(0);
        if e != a {
            deltas.push(format!(
                "  edge[{edge_type}]: expected {e}, got {a} (delta {:+})",
                a as i64 - e as i64
            ));
        }
    }

    // required_nodes / required_edges checks are no-ops today (both
    // vectors are empty for baseline fixtures). Later phases populate
    // them and this harness must diff them — stubbed here so the
    // structural shape is stable.
    for req in &expected.required_nodes {
        if !actual.required_nodes.contains(req) {
            deltas.push(format!("  missing required node: {req:?}"));
        }
    }
    for req in &expected.required_edges {
        if !actual.required_edges.contains(req) {
            deltas.push(format!("  missing required edge: {req:?}"));
        }
    }

    deltas
}

/// Test entry point shared by every fixture function. Runs the pipeline
/// against the named fixture and either (a) compares against
/// `expected.json` or (b) regenerates it when `SPACEBOT_PARITY_REGEN`
/// is set.
async fn run_parity(fixture_name: &str) -> Result<()> {
    let fixture_dir = fixtures_root().join(fixture_name);
    anyhow::ensure!(
        fixture_dir.is_dir(),
        "fixture '{fixture_name}' not found at {}",
        fixture_dir.display()
    );
    let expected_path = fixture_dir.join("expected.json");

    let actual = run_pipeline_on_fixture(&fixture_dir).await?;

    if std::env::var("SPACEBOT_PARITY_REGEN").is_ok() {
        let json = serde_json::to_string_pretty(&actual)? + "\n";
        std::fs::write(&expected_path, json)
            .with_context(|| format!("writing {}", expected_path.display()))?;
        eprintln!("regenerated expected.json for fixture '{fixture_name}'");
        return Ok(());
    }

    let expected_json = std::fs::read_to_string(&expected_path).with_context(|| {
        format!(
            "reading expected.json for fixture '{fixture_name}' at {} (run with SPACEBOT_PARITY_REGEN=1 to seed)",
            expected_path.display()
        )
    })?;
    let expected: ParityReport = serde_json::from_str(&expected_json)
        .with_context(|| format!("parsing expected.json for fixture '{fixture_name}'"))?;

    let deltas = diff_reports(&expected, &actual);
    if !deltas.is_empty() {
        let rendered = deltas.join("\n");
        panic!(
            "parity mismatch for fixture '{fixture_name}':\n{rendered}\n\nto accept these changes, rerun with SPACEBOT_PARITY_REGEN=1"
        );
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Per-fixture test entry points
// ---------------------------------------------------------------------------

#[tokio::test]
async fn parity_rust_basic() -> Result<()> {
    run_parity("rust_basic").await
}

#[tokio::test]
async fn parity_python_basic() -> Result<()> {
    run_parity("python_basic").await
}

#[tokio::test]
async fn parity_typescript_basic() -> Result<()> {
    run_parity("typescript_basic").await
}

#[tokio::test]
async fn parity_go_basic() -> Result<()> {
    run_parity("go_basic").await
}

#[tokio::test]
async fn parity_markdown_docs() -> Result<()> {
    run_parity("markdown_docs").await
}
