//! Centralized text registry for all prompts, tool descriptions, and fragments.
//!
//! This module provides compile-time embedding of all language variants,
//! with runtime selection via a global OnceLock.
//!
//! # Usage
//!
//! ```rust
//! // At startup (main.rs):
//! spacebot::prompts::text::init("en").expect("invalid language");
//!
//! // Anywhere:
//! let desc = spacebot::prompts::text::get("tools/file");
//! let prompt = spacebot::prompts::text::get("channel");
//! ```

use std::sync::OnceLock;

static LANGUAGE: OnceLock<String> = OnceLock::new();

/// Initialize the language for text lookups.
/// Must be called once at startup before any text lookups occur.
/// Returns Err if the language code is not supported.
pub fn init(language: &str) -> anyhow::Result<()> {
    // Currently only "en" is supported, but we validate the format
    // and set up the infrastructure for future languages
    if language != "en" {
        tracing::warn!(
            language = language,
            "non-English language requested, falling back to English"
        );
    }

    LANGUAGE
        .set(language.to_string())
        .map_err(|_| anyhow::anyhow!("language already initialized"))?;

    Ok(())
}

/// Get the configured language code.
fn language() -> &'static str {
    LANGUAGE.get().map(|s| s.as_str()).unwrap_or("en")
}

/// Get text for the given key in the configured language.
/// Falls back to English if the language or key is not found.
pub fn get(key: &str) -> &'static str {
    lookup(language(), key)
}

/// Lookup function generated by the macro.
/// Matches on (language, key) pairs.
fn lookup(lang: &str, key: &str) -> &'static str {
    match (lang, key) {
        // Process Prompts
        ("en", "channel") => include_str!("../../prompts/en/channel.md.j2"),
        ("en", "autonomy_channel") => include_str!("../../prompts/en/autonomy_channel.md.j2"),
        ("en", "branch") => include_str!("../../prompts/en/branch.md.j2"),
        ("en", "worker") => include_str!("../../prompts/en/worker.md.j2"),
        ("en", "cortex") => include_str!("../../prompts/en/cortex.md.j2"),
        ("en", "cortex_intraday_synthesis") => {
            include_str!("../../prompts/en/cortex_intraday_synthesis.md.j2")
        }
        ("en", "cortex_daily_summary") => {
            include_str!("../../prompts/en/cortex_daily_summary.md.j2")
        }
        ("en", "cortex_profile") => include_str!("../../prompts/en/cortex_profile.md.j2"),
        ("en", "compactor") => include_str!("../../prompts/en/compactor.md.j2"),
        ("en", "chronicle_checkpoint") => {
            include_str!("../../prompts/en/chronicle_checkpoint.md.j2")
        }
        ("en", "chronicle_rollup") => include_str!("../../prompts/en/chronicle_rollup.md.j2"),
        ("en", "memory_persistence") => include_str!("../../prompts/en/memory_persistence.md.j2"),
        ("en", "ingestion") => include_str!("../../prompts/en/ingestion.md.j2"),
        ("en", "cortex_chat") => include_str!("../../prompts/en/cortex_chat.md.j2"),
        ("en", "factory") => include_str!("../../prompts/en/factory.md.j2"),

        // Adapter-specific prompt fragments
        ("en", "adapters/email") => include_str!("../../prompts/en/adapters/email.md.j2"),
        ("en", "adapters/cron") => include_str!("../../prompts/en/adapters/cron.md.j2"),
        ("en", "adapters/signal") => include_str!("../../prompts/en/adapters/signal.md.j2"),
        ("en", "adapters/discord") => include_str!("../../prompts/en/adapters/discord.md.j2"),
        ("en", "adapters/slack") => include_str!("../../prompts/en/adapters/slack.md.j2"),
        ("en", "adapters/telegram") => include_str!("../../prompts/en/adapters/telegram.md.j2"),
        ("en", "adapters/mattermost") => include_str!("../../prompts/en/adapters/mattermost.md.j2"),
        ("en", "adapters/portal") => include_str!("../../prompts/en/adapters/portal.md.j2"),
        ("en", "adapters/twitch") => include_str!("../../prompts/en/adapters/twitch.md.j2"),
        ("en", "adapters/webhook") => include_str!("../../prompts/en/adapters/webhook.md.j2"),

        // Slash-command agent-turn instructions
        ("en", "commands/tasks") => include_str!("../../prompts/en/commands/tasks.md.j2"),
        ("en", "commands/today") => include_str!("../../prompts/en/commands/today.md.j2"),
        ("en", "commands/digest") => include_str!("../../prompts/en/commands/digest.md.j2"),

        // Fragment Templates
        ("en", "fragments/worker_capabilities") => {
            include_str!("../../prompts/en/fragments/worker_capabilities.md.j2")
        }
        ("en", "fragments/conversation_context") => {
            include_str!("../../prompts/en/fragments/conversation_context.md.j2")
        }
        ("en", "fragments/skills_channel") => {
            include_str!("../../prompts/en/fragments/skills_channel.md.j2")
        }
        ("en", "fragments/skills_worker") => {
            include_str!("../../prompts/en/fragments/skills_worker.md.j2")
        }
        ("en", "fragments/skills_branch") => {
            include_str!("../../prompts/en/fragments/skills_branch.md.j2")
        }
        ("en", "tools/skill_manage") => {
            include_str!("../../prompts/en/tools/skill_manage_description.md.j2")
        }
        ("en", "tools/skills_list") => {
            include_str!("../../prompts/en/tools/skills_list_description.md.j2")
        }
        ("en", "fragments/available_channels") => {
            include_str!("../../prompts/en/fragments/available_channels.md.j2")
        }
        ("en", "fragments/execution_standard") => {
            include_str!("../../prompts/en/fragments/execution_standard.md.j2")
        }
        ("en", "fragments/execution_direct") => {
            include_str!("../../prompts/en/fragments/execution_direct.md.j2")
        }
        ("en", "fragments/authority") => include_str!("../../prompts/en/fragments/authority.md.j2"),

        // System Message Fragments
        ("en", "fragments/system/retrigger") => {
            include_str!("../../prompts/en/fragments/system/retrigger.md.j2")
        }
        ("en", "fragments/system/retrigger_autonomy") => {
            include_str!("../../prompts/en/fragments/system/retrigger_autonomy.md.j2")
        }
        ("en", "fragments/system/truncation") => {
            include_str!("../../prompts/en/fragments/system/truncation.md.j2")
        }
        ("en", "fragments/system/worker_overflow") => {
            include_str!("../../prompts/en/fragments/system/worker_overflow.md.j2")
        }
        ("en", "fragments/system/worker_compact") => {
            include_str!("../../prompts/en/fragments/system/worker_compact.md.j2")
        }
        ("en", "fragments/system/memory_persistence") => {
            include_str!("../../prompts/en/fragments/system/memory_persistence.md.j2")
        }
        ("en", "fragments/system/memory_persistence_contract_retry") => {
            include_str!(
                "../../prompts/en/fragments/system/memory_persistence_contract_retry.md.j2"
            )
        }
        ("en", "fragments/system/autonomy_contract_retry") => {
            include_str!("../../prompts/en/fragments/system/autonomy_contract_retry.md.j2")
        }
        ("en", "fragments/system/autonomy_soft_warning") => {
            include_str!("../../prompts/en/fragments/system/autonomy_soft_warning.md.j2")
        }
        ("en", "fragments/system/autonomy_hard_timeout") => {
            include_str!("../../prompts/en/fragments/system/autonomy_hard_timeout.md.j2")
        }
        ("en", "fragments/system/profile_synthesis") => {
            include_str!("../../prompts/en/fragments/system/profile_synthesis.md.j2")
        }
        ("en", "fragments/system/ingestion_chunk") => {
            include_str!("../../prompts/en/fragments/system/ingestion_chunk.md.j2")
        }
        ("en", "fragments/system/history_backfill") => {
            include_str!("../../prompts/en/fragments/system/history_backfill.md.j2")
        }
        ("en", "fragments/system/tool_syntax_correction") => {
            include_str!("../../prompts/en/fragments/system/tool_syntax_correction.md.j2")
        }
        ("en", "fragments/tool_use_enforcement") => {
            include_str!("../../prompts/en/fragments/tool_use_enforcement.md.j2")
        }
        // Agent Communication Fragments
        ("en", "fragments/org_context") => {
            include_str!("../../prompts/en/fragments/org_context.md.j2")
        }
        // Coalesce Hint
        ("en", "fragments/coalesce_hint") => {
            include_str!("../../prompts/en/fragments/coalesce_hint.md.j2")
        }
        // Projects Context
        ("en", "fragments/projects_context") => {
            include_str!("../../prompts/en/fragments/projects_context.md.j2")
        }
        ("en", "fragments/opencode_task_management") => {
            include_str!("../../prompts/en/fragments/opencode_task_management.md.j2")
        }

        // Tool Descriptions
        ("en", "tools/reply") => include_str!("../../prompts/en/tools/reply_description.md.j2"),
        ("en", "tools/branch") => include_str!("../../prompts/en/tools/branch_description.md.j2"),
        ("en", "tools/spawn_worker") => {
            include_str!("../../prompts/en/tools/spawn_worker_description.md.j2")
        }
        ("en", "tools/route") => include_str!("../../prompts/en/tools/route_description.md.j2"),
        ("en", "tools/cancel") => include_str!("../../prompts/en/tools/cancel_description.md.j2"),
        ("en", "tools/skip") => include_str!("../../prompts/en/tools/skip_description.md.j2"),
        ("en", "tools/react") => include_str!("../../prompts/en/tools/react_description.md.j2"),
        ("en", "tools/set_outcome") => {
            include_str!("../../prompts/en/tools/set_outcome_description.md.j2")
        }
        ("en", "tools/set_status") => {
            include_str!("../../prompts/en/tools/set_status_description.md.j2")
        }
        ("en", "tools/shell") => include_str!("../../prompts/en/tools/shell_description.md.j2"),
        ("en", "tools/set_home_channel") => {
            include_str!("../../prompts/en/tools/set_home_channel_description.md.j2")
        }
        ("en", "tools/restart") => {
            include_str!("../../prompts/en/tools/restart_description.md.j2")
        }
        ("en", "tools/install_skill") => {
            include_str!("../../prompts/en/tools/install_skill_description.md.j2")
        }
        ("en", "tools/file_read") => {
            include_str!("../../prompts/en/tools/file_read_description.md.j2")
        }
        ("en", "tools/file_write") => {
            include_str!("../../prompts/en/tools/file_write_description.md.j2")
        }
        ("en", "tools/file_edit") => {
            include_str!("../../prompts/en/tools/file_edit_description.md.j2")
        }
        ("en", "tools/file_list") => {
            include_str!("../../prompts/en/tools/file_list_description.md.j2")
        }
        ("en", "tools/browser") => include_str!("../../prompts/en/tools/browser_description.md.j2"),
        ("en", "tools/web_search") => {
            include_str!("../../prompts/en/tools/web_search_description.md.j2")
        }
        ("en", "tools/memory_save") => {
            include_str!("../../prompts/en/tools/memory_save_description.md.j2")
        }
        ("en", "tools/memory_persistence_complete") => {
            include_str!("../../prompts/en/tools/memory_persistence_complete_description.md.j2")
        }
        ("en", "tools/autonomy_complete") => {
            include_str!("../../prompts/en/tools/autonomy_complete_description.md.j2")
        }
        ("en", "tools/memory_recall") => {
            include_str!("../../prompts/en/tools/memory_recall_description.md.j2")
        }
        ("en", "tools/memory_delete") => {
            include_str!("../../prompts/en/tools/memory_delete_description.md.j2")
        }
        ("en", "tools/memory_consolidate") => {
            include_str!("../../prompts/en/tools/memory_consolidate_description.md.j2")
        }
        ("en", "tools/channel_recall") => {
            include_str!("../../prompts/en/tools/channel_recall_description.md.j2")
        }
        ("en", "tools/chronicle") => {
            include_str!("../../prompts/en/tools/chronicle_description.md.j2")
        }
        ("en", "tools/email_search") => {
            include_str!("../../prompts/en/tools/email_search_description.md.j2")
        }
        ("en", "tools/worker_inspect") => {
            include_str!("../../prompts/en/tools/worker_inspect_description.md.j2")
        }
        ("en", "tools/send_file") => {
            include_str!("../../prompts/en/tools/send_file_description.md.j2")
        }
        ("en", "tools/cron") => include_str!("../../prompts/en/tools/cron_description.md.j2"),
        ("en", "tools/send_message_to_another_channel") => {
            include_str!("../../prompts/en/tools/send_message_description.md.j2")
        }
        ("en", "tools/secret_set") => {
            include_str!("../../prompts/en/tools/secret_set_description.md.j2")
        }
        ("en", "tools/send_agent_message") => {
            include_str!("../../prompts/en/tools/send_agent_message_description.md.j2")
        }
        ("en", "tools/wiki_create") => {
            include_str!("../../prompts/en/tools/wiki_create_description.md.j2")
        }
        ("en", "tools/wiki_edit") => {
            include_str!("../../prompts/en/tools/wiki_edit_description.md.j2")
        }
        ("en", "tools/wiki_read") => {
            include_str!("../../prompts/en/tools/wiki_read_description.md.j2")
        }
        ("en", "tools/wiki_list") => {
            include_str!("../../prompts/en/tools/wiki_list_description.md.j2")
        }
        ("en", "tools/wiki_search") => {
            include_str!("../../prompts/en/tools/wiki_search_description.md.j2")
        }
        ("en", "tools/wiki_history") => {
            include_str!("../../prompts/en/tools/wiki_history_description.md.j2")
        }
        ("en", "tools/task_create") => {
            include_str!("../../prompts/en/tools/task_create_description.md.j2")
        }
        ("en", "tools/task_list") => {
            include_str!("../../prompts/en/tools/task_list_description.md.j2")
        }
        ("en", "tools/task_update") => {
            include_str!("../../prompts/en/tools/task_update_description.md.j2")
        }
        ("en", "tools/task_history") => {
            include_str!("../../prompts/en/tools/task_history_description.md.j2")
        }
        ("en", "tools/add_task_comment") => {
            include_str!("../../prompts/en/tools/add_task_comment_description.md.j2")
        }
        ("en", "tools/goal_create") => {
            include_str!("../../prompts/en/tools/goal_create_description.md.j2")
        }
        ("en", "tools/goal_list") => {
            include_str!("../../prompts/en/tools/goal_list_description.md.j2")
        }
        ("en", "tools/goal_update") => {
            include_str!("../../prompts/en/tools/goal_update_description.md.j2")
        }
        ("en", "tools/skills_search") => {
            include_str!("../../prompts/en/tools/skills_search_description.md.j2")
        }
        ("en", "tools/spacebot_docs") => {
            include_str!("../../prompts/en/tools/spacebot_docs_description.md.j2")
        }
        ("en", "tools/config_inspect") => {
            include_str!("../../prompts/en/tools/config_inspect_description.md.j2")
        }
        ("en", "tools/factory_list_presets") => {
            include_str!("../../prompts/en/tools/factory_list_presets_description.md.j2")
        }
        ("en", "tools/factory_load_preset") => {
            include_str!("../../prompts/en/tools/factory_load_preset_description.md.j2")
        }
        ("en", "tools/factory_search_context") => {
            include_str!("../../prompts/en/tools/factory_search_context_description.md.j2")
        }
        ("en", "tools/factory_create_agent") => {
            include_str!("../../prompts/en/tools/factory_create_agent_description.md.j2")
        }
        ("en", "tools/factory_update_identity") => {
            include_str!("../../prompts/en/tools/factory_update_identity_description.md.j2")
        }
        ("en", "tools/factory_update_config") => {
            include_str!("../../prompts/en/tools/factory_update_config_description.md.j2")
        }
        ("en", "tools/project_manage") => {
            include_str!("../../prompts/en/tools/project_manage_description.md.j2")
        }
        ("en", "tools/ask") => include_str!("../../prompts/en/tools/ask_description.md.j2"),
        ("en", "tools/attachment_recall") => {
            include_str!("../../prompts/en/tools/attachment_recall_description.md.j2")
        }

        // Fallback: unknown language or key -> try English
        (lang, key) if lang != "en" => {
            tracing::warn!(
                lang,
                key,
                "text not found for language, falling back to English"
            );
            lookup("en", key)
        }

        // Unknown key in English
        _ => {
            tracing::error!(key, "unknown text key");
            ""
        }
    }
}
